name: Deploy on Push

on:
  push:
    branches: [ "master", "dev"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install -r source/requirements.txt

      - name: Run linter - hard errors only
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Run linter - soft style guide
        run: |
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics

  deploy:
    if: github.ref == 'refs/heads/master'
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Execute SSH Commands
        uses: GPTED/SSH-My-Action@0.1
        with:
          HOST: ${{ secrets.SSH_HOST }}
          USER: bot_dev
          PORT: ${{ secrets.PORT }}
          PRIVATE_KEY: ${{ secrets.BOT_DEV_SSH_PRIVATE_KEY }}
          CMD: |
            cd /srv/bots/vk-itmocraft/app;
            git reset --hard HEAD;
            git pull;
            cd /srv/bots/vk-itmocraft;
            podman-compose up -d --build --force-recreate;
